"""initial models with enums

Revision ID: 96efaa822f41
Revises: 
Create Date: 2026-03-29 14:06:54.501475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96efaa822f41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extratos_bancarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('processado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finalidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finalidades_id'), 'finalidades', ['id'], unique=False)
    op.create_index(op.f('ix_finalidades_nome'), 'finalidades', ['nome'], unique=True)
    op.create_table('lancamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finalidade_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', postgresql.ENUM('RECEITA', 'DESPESA', name='tipo_lancamento'), nullable=False),
    sa.Column('forma_pagamento', postgresql.ENUM('PIX', 'DINHEIRO', 'CARTAO_CREDITO', 'CARTAO_DEBITO', name='forma_pagamento'), nullable=False),
    sa.Column('status', postgresql.ENUM('CONCILIADO', 'NAO_CONCILIADO', name='status_lancamento'), server_default='NAO_CONCILIADO', nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=False),
    sa.Column('hash_transacao', sa.String(length=255), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['finalidade_id'], ['finalidades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_transacao')
    )
    op.create_index('idx_lancamento_data', 'lancamentos', ['data_pagamento'], unique=False)
    op.create_index('idx_lancamento_status', 'lancamentos', ['status'], unique=False)
    op.create_index('idx_lancamento_tipo', 'lancamentos', ['tipo'], unique=False)
    op.create_index(op.f('ix_lancamentos_id'), 'lancamentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lancamentos_id'), table_name='lancamentos')
    op.drop_index('idx_lancamento_tipo', table_name='lancamentos')
    op.drop_index('idx_lancamento_status', table_name='lancamentos')
    op.drop_index('idx_lancamento_data', table_name='lancamentos')
    op.drop_table('lancamentos')
    op.drop_index(op.f('ix_finalidades_nome'), table_name='finalidades')
    op.drop_index(op.f('ix_finalidades_id'), table_name='finalidades')
    op.drop_table('finalidades')
    op.drop_table('extratos_bancarios')
    # ### end Alembic commands ###
