"""incluindo sugestão de finalidade baseado na descricao de um lancamento

Revision ID: c6e82d177d5e
Revises: f86ce7b12639
Create Date: 2026-04-14 03:00:41.807472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e82d177d5e'
down_revision: Union[str, Sequence[str], None] = 'f86ce7b12639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lancamentos', sa.Column('sugestao_finalidade_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lancamentos', 'finalidades', ['sugestao_finalidade_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lancamentos', type_='foreignkey')
    op.drop_column('lancamentos', 'sugestao_finalidade_id')
    # ### end Alembic commands ###
