"""add status to extrato

Revision ID: f86ce7b12639
Revises: 96efaa822f41
Create Date: 2026-04-14 01:35:48.285976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f86ce7b12639'
down_revision: Union[str, Sequence[str], None] = '96efaa822f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 🔥 1. cria o ENUM primeiro
    status_enum = postgresql.ENUM(
        'PROCESSANDO',
        'PROCESSADO',
        'ERRO',
        name='status_processamento'
    )

    status_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extratos_bancarios', sa.Column('status', postgresql.ENUM('PROCESSANDO', 'PROCESSADO', 'ERRO', name='status_processamento'), server_default='PROCESSANDO', nullable=False))
    op.drop_constraint(op.f('lancamentos_hash_transacao_key'), 'lancamentos', type_='unique')
    op.create_index(op.f('ix_lancamentos_hash_transacao'), 'lancamentos', ['hash_transacao'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lancamentos_hash_transacao'), table_name='lancamentos')
    op.create_unique_constraint(op.f('lancamentos_hash_transacao_key'), 'lancamentos', ['hash_transacao'], postgresql_nulls_not_distinct=False)
    op.drop_column('extratos_bancarios', 'status')
    
    # 🔥 2. remove o ENUM (se não estiver em uso)
    status_enum = postgresql.ENUM(
        'PROCESSANDO',
        'PROCESSADO',
        'ERRO',
        name='status_processamento'
    )

    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
